version: '3.4'

services:
  urlShortener:
    image: urlshortener
    container_name: UrlShortener.Api
    build:
      context: .
      dockerfile: UrlShortener/Dockerfile
    ports:
      - "5001:443"

  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: urlshortener_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 1432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local